### ISSUE TITLE
Requests Max retries exceeded errors in 1.0.2

### ISSUE THREAD

**Issue by chewblacka** [Vanilla-OS/apx-gui#62]
Hi I've just updated the nix package for apx-gui  to 1.0.2 (had to add python requests as a new dependency). The project builds and seems to runs fine, but after a few seconds it spits out the below error. Is this a bug or am I missing a dependency? Many thanks!

    ERROR:Vanilla::Async:Error while running async job: <function Monitor.read at 0x7fb1346f72e0>
    Exception: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /events?  since=2024-07-09T16:35:01&stream=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb134703830>: Failed to establish a new connection: [Errno 111] Connection refused'))
    File "/nix/store/h1mwd3ndnhly81gn0as7i2fic3vhiqi5-apx-gui-1.0.2/share/apx_gui/apx_gui/core/run_async.py", line 73, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/h1mwd3ndnhly81gn0as7i2fic3vhiqi5-apx-gui-1.0.2/share/apx_gui/apx_gui/core/monitor.py", line 107, in read
    response = session.get(
               ^^^^^^^^^^^^
    File "/nix/store/f98z9h1gappf14p3id6kl21agfg9mfhp-python3-3.12.4-env/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/f98z9h1gappf14p3id6kl21agfg9mfhp-python3-3.12.4-env/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/f98z9h1gappf14p3id6kl21agfg9mfhp-python3-3.12.4-env/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/f98z9h1gappf14p3id6kl21agfg9mfhp-python3-3.12.4-env/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
    Traceback (most recent call last):
    File "/nix/store/h1mwd3ndnhly81gn0as7i2fic3vhiqi5-apx-gui-1.0.2/share/apx_gui/apx_gui/windows/main_window.py", line 70, in callback
    for event in events:
    TypeError: 'NoneType' object is not iterable

**Comment by mirkobrombin** [comment]
We uses the podman local server to check if the containers are running. Maybe podman is not installed or the server is not up?

We could consider to disable that feature if the server is not available.

**Comment by rotlir** [comment]
I have the same issue with 1.0.3. Podman is installed, and I was able to successfully install Chromium via apx and export it to my system. However, when I launch apx-gui I keep getting this error: 
```
ERROR:Vanilla::Async:Error while running async job: <function Monitor.read at 0x7080319be160>
Exception: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /events?since=2024-08-09T08:25:26&stream=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7080318cfb30>: Failed to establish a new connection: [Errno 111] Connection refused'))
  File "/usr/local/share/apx_gui/apx_gui/core/run_async.py", line 73, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/apx_gui/apx_gui/core/monitor.py", line 107, in read
    response = session.get(
               ^^^^^^^^^^^^
  File "/home/rotlir/.local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rotlir/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rotlir/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rotlir/.local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
Traceback (most recent call last):
  File "/usr/local/share/apx_gui/apx_gui/windows/main_window.py", line 70, in callback
    for event in events:
TypeError: 'NoneType' object is not iterable
```
My system is Arch linux. I built and installed apx-gui following the commands in README.

**Comment by CosmicFusion** [comment]
same here

**Comment by ivanucherdzhiev** [comment]
First of all thank you for the great project! 
I have same problem, the gui works, but it spits that error all the time and the status of subsystem (container) is not updated unless gui is restarted 

podman.socket is up 

Where might be the problem?
