### ISSUE TITLE
creating stacks hangs

### ISSUE THREAD

**Issue by jardon** [Vanilla-OS/apx-gui#74]
The stack is created successfully, but its never reported back correctly so the sub window never closes.
![image](https://github.com/user-attachments/assets/1ef315ec-54a3-4ad6-a048-a7ba726a20c6)

```
ERROR:Vanilla::Async:Error while running async job: <function CreateStackWindow.__on_create_clicked.<locals>.create_stack at 0x7f30e15428e0>
Exception: Expecting value: line 1 column 1 (char 0)
  File "/usr/local/share/apx_gui/apx_gui/core/run_async.py", line 73, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/apx_gui/apx_gui/windows/create_stack.py", line 109, in create_stack
    return stack.create()
           ^^^^^^^^^^^^^^
  File "/usr/local/share/apx_gui/apx_gui/core/apx_entities.py", line 151, in create
    stacks = json.loads(list_res[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
Traceback (most recent call last):
  File "/usr/local/share/apx_gui/apx_gui/windows/create_stack.py", line 88, in on_callback
    status: bool = result[0]
                   ~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jardon** [comment]
ill need to confirm, but i believe this is an issue with apx.  i think the buffer size needs to be increased further

```
      list_res[1]
'error reading binaries: bufio.Scanner: token too long\n[\n  {\n    "Name": "bionic-test-2",\n    "Base": "ubuntu:bionic",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "bionic-test-3",\n    "Base": "ubuntu:bionic",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "bionic-test-4",\n    "Base": "ubuntu:bionic",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "bionic-test",\n    "Base": "ubuntu-bionic",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "bionic",\n    "Base": "ubuntu:bionic",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "bluefin",\n    "Base": "ghcr.io/ublue-os/bluefin",\n    "Packages": [],\n    "PkgManager": "dnf",\n    "BuiltIn": false\n  },\n  {\n    "Name": "jammy",\n    "Base": "ubuntu:jammy",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "neon",\n    "Base": "invent-registry.kde.org/neon/docker-images/plasma:latest",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "noble",\n    "Base": "ubuntu:noble",\n    "Packages": [\n      "git",\n      "neofetch",\n      "vim"\n    ],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "sid",\n    "Base": "docker.io/library/debian:unstable",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": false\n  },\n  {\n    "Name": "ucore",\n    "Base": "ghcr.io/ublue-os/ucore",\n    "Packages": [],\n    "PkgManager": "dnf",\n    "BuiltIn": false\n  },\n  {\n    "Name": "alpine",\n    "Base": "alpine:latest",\n    "Packages": [],\n    "PkgManager": "apk",\n    "BuiltIn": true\n  },\n  {\n    "Name": "arch",\n    "Base": "ghcr.io/archlinux/archlinux:multilib-devel",\n    "Packages": [],\n    "PkgManager": "pacman",\n    "BuiltIn": true\n  },\n  {\n    "Name": "fedora",\n    "Base": "fedora:latest",\n    "Packages": [],\n    "PkgManager": "dnf",\n    "BuiltIn": true\n  },\n  {\n    "Name": "opensuse",\n    "Base": "registry.opensuse.org/opensuse/tumbleweed:latest",\n    "Packages": [],\n    "PkgManager": "zypper",\n    "BuiltIn": true\n  },\n  {\n    "Name": "ubuntu",\n    "Base": "ubuntu:latest",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": true\n  },\n  {\n    "Name": "vanilla-dev",\n    "Base": "ghcr.io/vanilla-os/dev:main",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": true\n  },\n  {\n    "Name": "vanilla",\n    "Base": "ghcr.io/vanilla-os/pico:main",\n    "Packages": [],\n    "PkgManager": "apt",\n    "BuiltIn": true\n  }\n]\n'
```

**Comment by jardon** [comment]
This may already be fixed with a previous commit, but we may be able to avoid these in the future by not sending stderr to subprocess.PIPE

**Comment by jardon** [comment]
sending `stderr` to `subprocess.NULL` doesnt work as the package manager logic seems to depend on it.  may need to rework that.
